# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: GITHUB_TOKEN

strategy:
  matrix:
    Python311:
      python.version: '3.11'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      # Obtener la versión de Chrome estable
      CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)

      # Obtener la versión correspondiente de ChromeDriver
      CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})

      echo "Chrome Version: $CHROME_VERSION"
      echo "ChromeDriver Version: $CHROMEDRIVER_VERSION"

      # Descargar ChromeDriver específico para la versión de Chrome
      wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -P ~/tmp
      unzip ~/tmp/chromedriver_linux64.zip -d ~/tmp
      sudo mv -f ~/tmp/chromedriver /usr/local/bin/chromedriver
      sudo chown root:root /usr/local/bin/chromedriver
      sudo chmod 0755 /usr/local/bin/chromedriver

      # Descargar e instalar Chrome estable
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo dpkg -i google-chrome-stable_current_amd64.deb
      sudo apt-get install -f -y
    displayName: 'Install Compatible Chrome and ChromeDriver'

  - script: |
      which google-chrome || echo "Google Chrome not found"
      which chromedriver || echo "ChromeDriver not found"
      google-chrome --version || echo "Unable to get Chrome version"
      chromedriver --version || echo "Unable to get ChromeDriver version"
    displayName: 'Check Chrome and ChromeDriver installation'

  - script: |
      nohup python app.py &
      sleep 10
      curl -I http://localhost:5000 || echo "Flask server not running"
    displayName: 'Start and Verify Flask Server'

  # Instalar herramientas de análisis estático
  - script: |
      pip install pylint bandit
    displayName: 'Install Static Analysis Tools'

    # Análisis de código con Pylint
  - script: |
      pylint $(Build.SourcesDirectory)/tpi_ahorcado \
        --output-format=junit > $(Build.SourcesDirectory)/pylint-report.xml
    displayName: 'Run Pylint Static Code Analysis'

  - script: |
      pip install pytest pytest-cov pytest-azurepipelines
      pytest --cov=. --cov-report xml
    displayName: 'Run tests with coverage'

  - script: |
      pip install -r requirements.txt
      pip install pytest pytest-cov pytest-azurepipelines
      pytest acceptance_tests.py --cov=. --cov-report xml --maxfail=3
    displayName: 'Run Acceptance Tests with coverage'

  - script: |
      git config --global user.name "guillermodolan"
      git config --global user.email "guillermo230899@gmail.com"

      git clone https://$(GITHUB_TOKEN)@github.com/guillermodolan/metodologias_agiles.git $(Build.SourcesDirectory)/repo

      cp -R $(Build.ArtifactStagingDirectory)/deploy $(Build.SourcesDirectory)/repo/deploy
      cd $(Build.SourcesDirectory)/repo
      git add deploy/
      git commit -m "Update deployment artifacts"
      git push origin main
    displayName: 'Push Deploy Artifacts to GitHub'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)/deploy
      cp -R $(Build.SourcesDirectory)/app.py $(Build.ArtifactStagingDirectory)/deploy/
      cp -R $(Build.SourcesDirectory)/requirements.txt $(Build.ArtifactStagingDirectory)/deploy/
    displayName: 'Prepare Deploy Artifact'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/deploy
      artifact: deploy
      publishLocation: 'pipeline'
    displayName: 'Publish Deploy Artifact'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish Test Results'
      testResultsFormat: 'JUnit'
    displayName: 'Publish test results'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/coverage.xml'
      reportDirectory: '$(Build.SourcesDirectory)/coverage-report'
    displayName: 'Publish Code Coverage Results'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-acceptance*.xml'
      testRunTitle: 'Acceptance Tests Results'
      testResultsFormat: 'JUnit'
    displayName: 'Publish Acceptance Test Results'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Build.SourcesDirectory)/pylint-report.xml'
      testRunTitle: 'Pylint Analysis Results'
    displayName: 'Publish Pylint Results'