# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'


- script: |
    pip install pylint
    pylint --exit-zero $(Build.SourcesDirectory)/tpi_ahorcado --output-format=parseable > $(Build.SourcesDirectory)/pylint-report.txt
  displayName: 'Run Pylint Static Code Analysis'

- script: |
    pip install pytest pytest-cov pytest-azurepipelines
    pytest --cov=. --cov-report xml
  displayName: 'Run tests with coverage'
  
  # Configurar git y subir el archivo a GitHub
- script: |
    # Configurar git
    git config --global user.name "Guillermo"
    git config --global user.email "guillermo230899@gmail.com"

    git clone https://$(GITHUB_TOKEN)@github.com/guillermodolan/metologias_agiles.git $(Build.SourcesDirectory)/repo

    mv $(Build.SourcesDirectory)/pylint-report.txt $(Build.SourcesDirectory)/repo/

    cd $(Build.SourcesDirectory)/repo
    git add pylint-report.txt
    git commit -m "Add pylint report"
    git push origin main
  displayName: 'Push Pylint Report to GitHub'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish Test Results'
    testResultsFormat: 'JUnit'
  displayName: 'Publish test results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage.xml'
    reportDirectory: '$(Build.SourcesDirectory)/coverage-report'
  displayName: 'Publish Code Coverage Results'

